# Generated by Django 5.1.2 on 2024-11-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0002_temporaryroleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary_role', models.CharField(choices=[('owner', 'owner'), ('manager', 'manager'), ('employee', 'employee')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_roles', to='celery_app.sellerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='TemporaryRoleAssignment',
        ),
    ]
