version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - celery_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    networks:
      - celery_network

  celery:
    build: .
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    command: celery -A celery_demo worker --loglevel=info
    depends_on:
      - rabbitmq
    networks:
      - celery_network

networks:
  celery_network:
    driver: bridge
